targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
        generate_for:
          - lib/models/**
          - lib/screens/**
      freezed:
        enabled: true
        options:
          json: false
        generate_for:
          - lib/models/**
          - lib/screens/**
